defaultPlacement: end
enableVersioning: true
handle: shows
name: Shows
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: shows/_entry
    uriFormat: 'shows/{slug}'
type: channel
