columnSuffix: vyvclyib
contentColumnType: text
fieldGroup: ee385c12-292c-400e-9595-82fcee199ea3 # Common
handle: description
instructions: null
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
