columnSuffix: erthjtog
contentColumnType: text
fieldGroup: 3d9a043a-c39e-45b0-87ca-848b7f08ee38 # Homepage
handle: headline
instructions: 'Headline on the homepage.'
name: Headline
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
