fieldLayouts:
  e8d80a46-8d34-4dda-9e06-841a096ba3d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f50ca55e-fc15-4312-8c80-e11a1584fa03
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3815405-6950-4df5-8e1e-6646ad9e3607 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 700c4a3e-4de9-4a59-a7e7-22bf3f266e41
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5b4c84db-5412-44b1-a47f-a6e46f8fb8b6 # Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 162b8f93-1530-4b8f-a2b6-e87b91b8c547
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: b3f68f95-32bc-4588-9620-b4235c1f4524
            userCondition: null
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  elementId: null
                  fieldUid: 5b4c84db-5412-44b1-a47f-a6e46f8fb8b6 # Location
                  operator: notempty
                  uid: db378519-2bf2-43bc-ac7a-abf8221b2ec4
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 135d7d84-4a62-4878-b0ee-2b68ceb36e5b # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb1dfe3c-c893-4e1f-aa72-1389c4ebe34b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65967dd5-d349-4697-9e13-29d17f2a6ae1
        userCondition: null
      -
        elementCondition:
          class: craft\elements\conditions\entries\EntryCondition
          conditionRules:
            -
              class: craft\fields\conditions\RelationalFieldConditionRule
              elementId: null
              fieldUid: 5b4c84db-5412-44b1-a47f-a6e46f8fb8b6 # Location
              operator: notempty
              uid: 6855e33b-eb82-4834-9e27-dfec3330da43
          elementType: craft\elements\Entry
          fieldContext: global
        elements:
          -
            elementCondition: null
            fieldUid: 38a6b564-bc0d-4c48-a475-a0414f026a39 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8623b396-ab04-40e1-a128-0e0001ca8f6e
            userCondition: null
            warning: null
            width: 100
        name: Images
        uid: e8649d81-cf43-4e43-9e59-965ff6c0e1bb
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 9ea4c123-33d6-4c84-ac57-369d91f98030 # Adventures
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
