dateModified: 1659545647
email:
  fromEmail: andrew@nystudio107.com
  fromName: Craft
  transportType: craft\mail\transportadapters\Sendmail
fs:
  site:
    hasUrls: true
    name: Site
    settings:
      path: '@webroot/assets/site'
    type: craft\fs\Local
    url: '@assetsUrl/assets/site'
meta:
  __names__:
    1bcc60f5-0699-49dd-8eff-672d2df43aa4: Homepage # Homepage
    3d9a043a-c39e-45b0-87ca-848b7f08ee38: Homepage # Homepage
    5c642d7e-b16b-4836-9575-668d75d242e5: Site # Site
    5f5284fc-b449-483f-ab7e-eb2ab59fc72d: Image # Image
    53ed4ec6-af5c-42a2-afad-80c9a997d531: 'Public Schema' # Public Schema
    0728feda-2f51-4566-a67f-7e3d1bd6ae5e: Headline # Headline
    a9a8c8df-e097-41ba-9ec2-7a8ec243f386: Homepage # Homepage
    c6f408b7-b5d0-47bd-9673-75a466d4df4a: Tagline # Tagline
    ee385c12-292c-400e-9595-82fcee199ea3: Common # Common
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  retryDuration: 60
  schemaVersion: 4.0.0.9
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
